### ISSUE TITLE
No Way to Break Out While Dragging. e.preventDefault and return false doesn't work.

### ISSUE THREAD

**Issue by thevinci** [seiyria/bootstrap-slider#295]
There is no way to break out a drag event. I have taken your code apart and can't seem to find any way to detect if you are dragging the min or max handles. obj evt needs to show which is being moved.

Also, e.preventDefault() and return false doesn't do what they are suppose to do.

**Comment by will-e-yams** [comment]
I'm going to jump on this to give some more information; just now, i ran into the same problem.

AFAIK, internal events and external events are separate. For example, clicking on the slider fires the internal event `_mousedown` which triggers the external event `slideStart`. Immediately after (line ~1119) triggering the external event, the internal event sets the new value. Externally, if you handle and `stopPropagation` of `slideStart` it does nothing to stop the setting of the value.

My suggestion would be to have internal functionality subscribe to the same external events. Functionality that changes the value after a `mousedown` event would simply be the first handler of `slideStart`.

--

My specific scenario was having a range slider with the lower handle disabled. Since I can't disable "half" of the control, I was going to handle the event, determine if it moved the upper or lower boundary and cancel it if it moved the lower.

**Comment by will-e-yams** [comment]
well, that's one way to resolve it.

**Comment by 0x1d** [comment]
i have a similar scenario:
instead of dragging, i want to prevent the outcome of the click / mousedown event.
as of today, i haven't seen a possibility to abort the mousedown event.
or am i missing something?

**Comment by storafrid** [comment]
Here is an (ugly) workaround that did the job for me:

```
$('#myInput').slider().on('change', function (e) {
    $('#myInput').slider('setValue', e.value.oldValue);
});
```
