### ISSUE TITLE
logarithmic scale not working with range selectors

### ISSUE THREAD

**Issue by baasdesign** [seiyria/bootstrap-slider#398]
I've got this slider for selecting ranges. But i need this to be logarithmic. Somehow its not working.

```
<input id="prijs-slider1" type="text" class="span2" value="" data-slider-min="{{lowPrice}}" data-slider-max="{{highPrice}}" data-slider-step="1" data-slider-value="[{{lowPrice}},{{highPrice}}]"/>
```

```
$("#prijs-slider1").slider({
        min: lowPrice,
        max: highPrice,
        scale: 'logarithmic',
        step: 10
    });
```

Is it because I am using variables?

**Comment by seiyria** [comment]
It looks like you're doing some templating there, possibly angular style? You might want to use the angular wrapper for that. Otherwise, you don't have to specify the options if you instantiate them in JS.

Ultimately, because you could be doing _so many things_, please provide a jsfiddle so I can actually see what you're doing.

**Comment by baasdesign** [comment]
Thanks for your reply. Let me put it this way:

Is it possible to have a logarythmic scale with a range selection? And if yes, is there an example somewhere?

**Comment by seiyria** [comment]
Theoretically it should be possible, yes, but we do not have any test cases or examples to cover this case, I believe.
