### ISSUE TITLE
Set empty value on max range

### ISSUE THREAD

**Issue by tfr** [seiyria/bootstrap-slider#403]
Is there a possibility or can somepoint point me to the correct place in code to change the behaviour so that in case the range slider is set to maximum range (val[0]==options.min, val[1]==options.max), the input value is set to empty, not "[min,max]" ?

**Comment by seiyria** [comment]
I don't  believe this is feasible, nor am I sure why you'd want to do this. This is something best reserved to your own value checking code.

**Comment by tfr** [comment]
I'm using this for a filter, and the min and max values are calculated dynamically upon filter rendering. Since the slider itself already has the information, I'd like to avoid unnecessary conditions in the query, or calculating those min/max values again.

I completely understand that this might not be a generally requested feature - hence I just asked for a pointer where the actual value for the <input> tag is set, as I didn't quite understand it from the code on the first glance. I have already rewritten parts of it for my own needs, so I might as well do that as well.

**Comment by tfr** [comment]
Managed to achieve it by adding this to the _setDataVal() function - don't know if it's the best and prettiest solution, but it does seem to get the job done:

```
if (this.options.range && val[0]==this.options.min && val[1]==this.options.max)
{
  this.element.setAttribute('value','');
  this.element.value = '';
}
else
{
  this.element.setAttribute('value', val);
  this.element.value = val;
}
```

**Comment by ronaldbarendse** [comment]
Since disabled input fields are not submitted, a better way would be to disable/enable the input on the `slide` event. No empty values are submitted and no changes to the original code is needed.

	var slider = $('input.slider').slider().data('slider');
	slider.on('slide', function (newValue) {
		$(slider.element).prop('disabled', slider.range && newValue[0] == slider.options.min && newValue[1] == slider.options.max);
	});
	
	// Fire initial slide event to set disabled state
	slider.setValue(slider.getValue(), true);

Instead of calling the `setValue` method to fire the initial `change` event, you could also disable the input server-side, although that would duplicate the logic (client and serverside/different languages) and require JavaScript to enable it again...

I've used the `slide` event here instead of the `change` event, because otherwise the initial event will not be fired (since the value stays the same). Maybe you could optimize this a little bit.
