### ISSUE TITLE
Load complete Event

### ISSUE THREAD

**Issue by myGitHubForum** [seiyria/bootstrap-slider#422]
Is there anyway I can know when the slider loading is complete? After initialization complete I want to trigger change event to zero index as it always pointing to the last index.

Also would appreciate if a sample code is provided how to trigger a change event how to set a value.

**Comment by myGitHubForum** [comment]
I have tried following to dynamically change the slider index. but giving me error.
cannot call methods on slider prior to initialization; attempted to call 'setValue'.

Any help will be appreciated. Thanks.

Code:
var mapsSlider;
                 $scope.runSlider = function() {
                        if ( angular.isDefined(mapsSlider) ) return;
                        var cnt = 1;
                        mapsSlider = $interval(function(){
                            console.log('TEST Run Slider: ' + cnt)
                            $('#maps-slider').slider('setValue',cnt);
                            if(cnt === $scope.timeline.ticks.length){
                                $scope.stopSliderRun();
                            }
                            cnt++;
                        },1000);
                    };

**Comment by seiyria** [comment]
If you're using angular, you may want to use [the angular directive](https://github.com/seiyria/angular-bootstrap-slider).

That said, if you're not using it for some reason, you can assume the slider is initialized after calling .slider on it. For anything further, I'm going to need to see a jsfiddle or plunker, because I don't get what you're doing or why you're doing it.
