### ISSUE TITLE
Tick label position is not correct

### ISSUE THREAD

**Issue by kanuj5212** [seiyria/bootstrap-slider#472]
I am using using seiyria/bootstrap-slider in which tick label is not correct.
Here is the fiddle:

https://jsfiddle.net/Anuj_Kumar/qn3u9orj/6/

**Comment by seiyria** [comment]
I don't know what version you're using, but this is Example 13, not 12, so I suspect it's outdated. Please update to the latest version and let me know if you still have problems.

**Comment by kanuj5212** [comment]
i have update the fiddle but still i am facing the issue

**Comment by seiyria** [comment]
What's probably happening, then, is that your tick values and labels are far too close in value. If you want to use this option then you will need to space out your tick values more, because the ticks are drawn correctly, the labels are not, but if they were drawn beneath their ticks, they would get squished.

**Comment by kanuj5212** [comment]
I have already tried by increasing the width of slider. But it's also not helping. It's same as before

**Comment by seiyria** [comment]
What I'm suggesting is not to increase the width of the slider, but to increase the distance between the ticks.

**Comment by kanuj5212** [comment]
Ahh it will be dynamic. I cannot make it fixed.

**Comment by seiyria** [comment]
Sorry, in that case, there's not a whole lot that can be done I'm afraid.
