### ISSUE TITLE
Max value cannot be reached

### ISSUE THREAD

**Issue by dartoism** [seiyria/bootstrap-slider#675]
Hi,

here is an example where it's impossible to slide to the max value: [https://fiddle.jshell.net/e0s0jfvx/1/](https://fiddle.jshell.net/e0s0jfvx/1/)

setup:

min value: 11350
max value: 29790
initial value: 29790
step: 100

To replicate:

slide to the left. Try to slide back to the max value. Slider stops at 29750. It's impossible to reach max value (29790).

**Comment by seiyria** [comment]
That's because it's not a multiple of 100 (your step size). This is intended behavior.

**Comment by dartoism** [comment]
If it's a feature and not a bug it's at least working inconsistently. I have updated the example. You can set the max value programmatically but you can't slide to it. Does it really make sense to you?

**Comment by seiyria** [comment]
I'll admit it is inconsistent, but imo I still stand by it - programmatic
access for most things is more powerful usually. If you want to compare it
to something, I would like to see what a normal slider (input type = range)
does.

On Fri, Dec 23, 2016, 00:43 dartoism <notifications@github.com> wrote:

If it's a feature and not a bug it's at least working inconsistently. I
have updated the example. You can set the max value programmatically but
you can't slide to it. Does it really make sense to you?

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/seiyria/bootstrap-slider/issues/675#issuecomment-268947504>,
or mute the thread

**Comment by dartoism** [comment]
If I change the slider-step value to 250 or 500, it does work.
It takes 190 for the last step if I set 250 and it takes 490 as a last step if I set 500.
Even when I set 50 it works...

Only when I set 100 as step, it doesn’t take 40 for the last step. It seems not to like 100…
I don’t get it. The other values are also not “mathematically compatible”.
