### ISSUE TITLE
Arrow Keys not working with Microsoft Edge

### ISSUE THREAD

**Issue by mrevjd** [seiyria/bootstrap-slider#777]
While doing some testing using Microsoft Edge I noticed the arrow keys do not adjust the slider value. 
This is the case using any of your examples on your demo page.

All other browsers I tested with including older IE versions work flawlessly.
 
Thanks

**Comment by rovolution** [comment]
we would welcome a PR that addresses this issue!

**Comment by armpogart** [comment]
Can't reproduce the beahavior in Edge (Microsoft Edge 41.16299.15.0), what version are you using, where keyboard arrows are not working. It works flawlessly here.

**Comment by mrevjd** [comment]
Microsoft Edge 40.15063.674.0.
Still doing it. All other browsers are fine.

**Comment by armpogart** [comment]
@mrevjd Unfortunately I don't have an older version of Windows to reproduce the behavior, I think it is some bug with the Edge (there were a few bugs that may be related to this problem and they were all fixed in Fall Creator's updated). Can't even test, find out which exact bug is it, to propose any solution :(

**Comment by mrevjd** [comment]
Just updated my Windows 10 and Microsoft Edge is now 41.16299.15.0. Unfortunately it is still doing it for me. All other browsers work fine. Strange issue.
The Up and Down arrow keys scroll the entire page. The left and right do nothing.

Cheers

**Comment by mrevjd** [comment]
Way too old now
