### ISSUE TITLE
When I set minimum possible value, the slider tick position is wrong

### ISSUE THREAD

**Issue by oo6** [seiyria/bootstrap-slider#914]
See https://jsfiddle.net/7robhqku/

![image](https://user-images.githubusercontent.com/6327995/53716201-1a0fcf80-3e8f-11e9-8601-c1d5bad1e3b2.png)

**Comment by jespirit** [comment]
I'll look at this later today. Thanks for jsfiddle.

**Comment by jespirit** [comment]
It turns out that what I think you're trying to do is not supported.

You can read this issue on how to set limits https://github.com/seiyria/bootstrap-slider/issues/651 because you can't use the `min` option with a tick that is less than the minimum value. It adversely affects tick position and calculating the value of the slider.

Here's another JSFiddle I modified for your case: https://jsfiddle.net/jespiritu/nqzru0by/1/

**Comment by seiyria** [comment]
Looks right. Thanks for the research @jespirit!
